### ISSUE TITLE
Hey Karl,

### ISSUE THREAD

**Issue by retorquere** [KarlHegbloom/zotero-texmacs-integration#1]

**Comment by KarlHegbloom** [comment]
What is it?

**Comment by retorquere** [comment]
Sorry, reformatted my question after I accidentally submitted it the first
time.

**Comment by retorquere** [comment]
And then I apparently I didn't submit the retyped the question. Sorry. Am I correct in understanding this is a drop-in replacement for bibtex? I'm toying with the idea of packing up citeproc-js to create a standalone drop-in replacement for bibtex. Is this script a straight transform from aux to bbl?

**Comment by retorquere** [comment]
Ah, I submitted it as a separate issue. I'll close this one.
